### ISSUE TITLE
BLOB CLOB SQLXMLのメタクラスが生成されない

### ISSUE THREAD

**Issue by master-of-sugar** [typesafe-query/typesafe-query#119]
対応漏れです。ハイ・・・。

**Comment by master-of-sugar** [comment]
```
メタクラスを作成できませんでした。
java.lang.RuntimeException: 対応していない型です java.sql.Blob
    at com.github.typesafe_query.tools.MetaProcessor.writeIDBColumn(MetaProcessor.java:605)
    at com.github.typesafe_query.tools.MetaProcessor.processType(MetaProcessor.java:221)
    at com.github.typesafe_query.tools.MetaProcessor.createMetaClass(MetaProcessor.java:126)
    at com.github.typesafe_query.tools.MetaProcessor.process(MetaProcessor.java:102)
    at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:139)
    at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:121)
    at org.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnn
```
